### PR TITLE
Removed all the unused imports 

### LINKED ISSUE #51: Many unused imports
**Describe the bug**
Unused imports
**To Reproduce**
The whole project consists of so many unused imports errors.

unused import

**Environment**
- Device/emulator being used: <device version/Pixel 2 XL>
- OS ( Android); If Android then android version: <Android : 11>
- Flutter version: <2.8>

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Pavel401**
Fixes #51
Describe the changes you have made in this PR -

 Removed all the unused imports .

### CODE REVIEW

**Comment by Erarshad** [comment]
upload the proof that it get compiled and works, because removing import is risky and i cannot merge without any proof

**Comment by Pavel401** [comment]
https://user-images.githubusercontent.com/47685150/150640107-f7242fb4-ae8d-4cd4-bc29-26e332cb0cb6.mp4
It's compiling.

**Comment by Erarshad** [comment]
put the snapshot or screen rec of terminal log, the vscode extension does not shows logs

**Comment by Pavel401** [comment]
image


> put the snapshot or screen rec of terminal log, the vscode extension does not shows logs

Before there were many lint errors and unused imports so I have added flutter_lints: ^1.0.4
and analysis_options.yaml to remove lint errors. Now 50  errors are there related to deprecated widgets.

**Pull request merged**
